-- Create a temporary table to hold the imported data
CREATE TEMP TABLE temp_entrants (
    first_name VARCHAR(255),
    last_name VARCHAR(255)
);

-- Insert all names from the provided list
INSERT INTO temp_entrants (first_name, last_name) VALUES
('ANDRE', 'VISSER'),
('ANDRE', 'VISSER'),
('KYLE', 'BELL'),
('OLANDO', 'FERDINANDO'),
('DALE', 'BEZUIDENHOUT'),
('LOUIS', 'KOTZE'),
('GEORGE', 'VAN DEVENTER'),
('TONY', 'HEENAN'),
('DUNCAN', 'SCHULTZ'),
('PHILLIP', 'GREGORY'),
('THOMAS', 'BOTHA'),
('FRANKE', 'HEFER'),
('ANDREW', 'KLOPPER'),
('KEVIN', 'BENOV'),
('ETIENNE', 'PARNAS'),
('THOMAS', 'NEL'),
('SANELE', 'SANTOSHA'),
('CARL', 'PETZER'),
('GYS', 'GEYSER'),
('HENRI', 'PREITNER'),
('JOHN', 'BOYES'),
('RICHARD', 'FISCHER'),
('LEON', 'PERSE'),
('LEONARD', 'GILFILLAND'),
('SEAN', 'CHATT'),
('ROB', 'HERSOV'),
('GLENN', 'NORMAN'),
('NICO', 'SCHUTTE'),
('ANDRE', 'VANHEERDEN'),
('CHRIS', 'POTTS'),
('GRAHAM', 'VEASLEY'),
('LEE', 'YEO'),
('ROBERT', 'SCHU'),
('MATT', 'VISSER'),
('MICHAEL', 'GRACE'),
('RUSSELL', 'COXFATHER'),
('RUSSELL', 'COOK'),
('HELGO', 'ROACH'),
('FARREL', 'FOUCHE'),
('PASSIE', 'CHOUDHARY'),
('NICO', 'MEYER'),
('MICHAEL', 'RUKE'),
('CHARL', 'FRUMAN'),
('PIETER', 'VENTER'),
('LUKE', 'HONEYMAN'),
('STEPHAN', 'NEWMAN'),
('PETER', 'RICHMULLLER'),
('STEVEN', 'KITTENT'),
('JUSTIN', 'DRYMEN'),
('COBUS', 'OOSTHUIZEN'),
('NEIL', 'HUDSON'),
('PIERRE', 'MALAN DE VRIES'),
('WAYNE', 'VOSS'),
('PHILIP', 'RAPPAPORT'),
('JANNIE', 'VOSSCHINK'),
('CORLIE', 'NAIKER'),
('COENIE', 'HEUSER'),
('CECIL', 'REED'),
('PETER', 'GOULD'),
('DOMENIC', 'HASSELBANK'),
('JAMES', 'HERBERT'),
('WARREN', 'NEL'),
('NICK', 'FRENCH'),
('WILLIAM', 'SPALL BERRY'),
('GEORGE', 'WILSON'),
('JANS VAN', 'WARREN'),
('KOBUS', 'NEL'),
('JASON', 'LLOYD'),
('DAVID', 'YOUNG'),
('PETE', 'VAN VUREN'),
('ARNOLD', 'VAN DER MERWE'),
('ALLAN', 'TORRES'),
('BYRON', 'HAWKINS'),
('DEJAN', 'CORNELIUS'),
('ITUMELK', 'VLAMINI'),
('PETER', 'GARDINER'),
('HERMAN', 'DAHN'),
('BRAD', 'RICHARDS'),
('LEON', 'LONFREN'),
('THEO', 'RADEMEYER'),
('THOMAS', 'HATTING'),
('GARETH', 'ELIASER'),
('HUGO', 'RADZILANI'),
('DONALD', 'DEACON'),
('WERNER', 'ROUX'),
('DANIE', 'ROUX'),
('KOBUS', 'VILJOEN'),
('MARC', 'WILLIS'),
('KEVIN', 'SMITH'),
('EUGENE', 'KINGHORN'),
('MARTIN', 'SCHINLAK'),
('FRANCOIS', 'VENTER'),
('DANIE', 'PFEIFFER'),
('DIJON', 'WILLES'),
('LEMIST', 'VAN DER BIJL'),
('GEORGE', 'ANDERSON'),
('JOHAN', 'SCHEEPERS'),
('WIMPIE', 'ALCAPPA'),
('ROGER', 'STEINHOFF'),
('DYLAN', 'MCLAUGHLIN'),
('GERRY', 'FOULSNER'),
('GERRY', 'BURGER'),
('MORNE', 'MARAIS'),
('PIERRE', 'MALAN'),
('HENK', 'SMITH'),
('GEORGE', 'WOLFARAFT'),
('SCHALK', 'CRONJE'),
('MARIUS', 'BEUKER'),
('MARIUS', 'OOSTUZHON'),
('WILLIE', 'VAN STADEN'),
('WILHELM', 'DUJTOIT'),
('WILHELM', 'LLISWINKL'),
('JAYMES', 'HAMMONS'),
('ANNELEN', 'DAHN'),
('RUDI', 'SPANNRATH'),
('ANTON', 'HARMSA'),
('CARMEN', 'HARDROFER'),
('COLIN', 'THORNE'),
('MICHAEL', 'VAN DER MERWE'),
('SAREL', 'KOTZE'),
('RICHARD', 'DOWNING'),
('DICK', 'MUIR'),
('DANIE', 'VERMEULEN'),
('PETER', 'ERESTER'),
('JACO', 'NEL'),
('ROB', 'BRAXTON'),
('THOMAS', 'BRETON'),
('ROBERTO', 'OGEMDAL'),
('JACQUES', 'VENTER'),
('MERVYN', 'EAGLES'),
('GLE', 'EASDALE'),
('MARCUS', 'VILJOEN'),
('WILLEM', 'ROAL'),
('PIET', 'ERASMUS'),
('WILLEM', 'VAN ZYL'),
('COLIN', 'HIBBERD'),
('EBEN', 'LIEBRICH'),
('PETER', 'MOTT');

-- Insert the data into the actual entrants table
-- This will generate a unique email for each entrant using first name and last name
INSERT INTO entrants ("firstName", "lastName", email, "updatedAt")
SELECT 
    first_name,
    last_name,
    LOWER(CONCAT(first_name, '.', last_name, '@example.com')) as email,
    NOW() as "updatedAt"
FROM temp_entrants 
ON CONFLICT (email) DO UPDATE
    SET "firstName" = EXCLUDED."firstName",
        "lastName" = EXCLUDED."lastName",
        "updatedAt" = NOW();

-- Clean up
DROP TABLE temp_entrants;

-- Return the count of inserted/updated records
SELECT COUNT(*) as "Entrants Processed" FROM entrants; 